FlowRouter.route('/',{
    name:'home',
    action(){
    BlazeLayout.render('home-layout');
}
});
FlowRouter.route('/home',{
    name:'home',
    action(){
    BlazeLayout.render('main-layout',{main:'learnace',footer:'main-footer'});
}
});